version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - esbuild
  - selfcheck
ignoreWords:
  - enabledelayedexpansion
  - endlocal
  - setlocal
  - errorlevel
  - findstr
import: []
