version: "0.2"
ignorePaths:
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - .prettierignore
dictionaryDefinitions: []
dictionaries: []
words:
  - classnames
  - esbuild
  - Hambak
  - Hambakneun
  - nanum
  - pixabay
  - selfcheck
ignoreWords:
  - enabledelayedexpansion
  - endlocal
  - setlocal
  - errorlevel
  - findstr
import: []
